fpq/fpq/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('fpq_core.urls')),
    *[
        path(f'{name}/', include(f'fpq_{name}.urls'))
        for name in ('user', 'author', 'quote')
    ],
    path('scrape/', include('fpq_scraper.urls')),
    path('admin/', admin.site.urls),
]

fpq/fpq_author/urls.py
from django.urls import path

from .views import CreationView, detail

app_name = 'fpq_author'

urlpatterns = [
    path('', CreationView.as_view(), name='create'),
    path('<int:author_id>/', detail, name='detail'),
]

fpq/fpq_core/urls.py
from django.urls import path

from .views import index

app_name = 'fpq_core'

urlpatterns = [
    path('', index, name='index'),
]

fpq/fpq_quote/urls.py
from django.urls import path

from .views import CreationView

app_name = 'fpq_quote'

urlpatterns = [
    path('', CreationView.as_view(), name='create'),
]

fpq/fpq_scraper/urls.py
from django.urls import path

from .views import scraping

app_name = 'fpq_scraper'

urlpatterns = [
    path('', scraping, name='scrape'),
]

fpq/fpq_user/urls.py
from django.contrib.auth.views import LoginView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordResetDoneView
from django.urls import path

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView, signout

app_name = 'fpq_user'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='fpq_user/login.html',
            form_class=LoginForm,
            redirect_authenticated_user=True,
        ),
        name='login',
    ),
    path('logout/', signout, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path(
        'reset-password/',
        ResetPasswordView.as_view(),
        name='password_reset',
    ),
    path(
        'reset-password/done/',
        PasswordResetDoneView.as_view(
            template_name='fpq_user/password_reset_done.html',
        ),
        name='password_reset_done',
    ),
    path(
        'reset-password/confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='fpq_user/password_reset_confirm.html',
            success_url='/user/reset-password/complete/',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset-password/complete/',
        PasswordResetCompleteView.as_view(
            template_name='fpq_user/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
]

fpq/fpq_core/models.py
from django.db import models

# Create your models here.

fpq/fpq_core/forms.py
from typing import Any


class FormHelper:
    def __init__(self, *args: tuple, **kwargs: dict) -> None:
        super().__init__(*args, **kwargs)

        self.validate(self)

    @staticmethod
    def attributes(identifier: str) -> dict:
        if not identifier:
            raise ValueError('The tag identifier can not be empty.')

        return {'id': identifier, 'class': 'form-control'}

    @staticmethod
    def validate(form: Any) -> None:
        for name, field in form.fields.items():
            if not form.errors.get(name):
                continue

            MAPPING = {
                'class': 'class',
                'id': 'aria-describedby',
            }

            for source, target in MAPPING.items():
                attribute = field.widget.attrs.get(source, '')
                field.widget.attrs[target] = attribute + ' is-invalid'

fpq/fpq_core/views.py
from abc import ABC, abstractmethod
from typing import Any

from django.core.handlers.wsgi import WSGIRequest
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count, F, Window
from django.db.models.functions import RowNumber
from django.forms import ModelForm
from django.http import HttpResponse, HttpResponsePermanentRedirect, QueryDict
from django.shortcuts import redirect, render
from django.views import View

from fpq_quote.models import Quote
from fpq_tag.models import Tag


Response = HttpResponse | HttpResponsePermanentRedirect


class FormView(ABC, View):
    def _context(self) -> dict:
        return dict()

    @abstractmethod
    def _guest(self) -> bool:
        ...

    def _save(
        self,
        response: QueryDict,
        form: ModelForm,
        commit: bool = True
    ) -> Any:
        return form.save(commit)

    def dispatch(self, request: WSGIRequest) -> Response:
        if request.user.is_anonymous == self._guest():
            return redirect('fpq_core:index')

        return super().dispatch(request)

    def get(self, request: WSGIRequest) -> HttpResponse:
        return render(
            request,
            self.template_name,
            {'form': self.form_class, **self._context()},
        )

    def post(self, request: WSGIRequest) -> Response:
        form = self.form_class(request.POST)

        if form.is_valid():
            self._save(request.POST, form)

            return redirect('fpq_core:index')

        return render(
            request,
            self.template_name,
            {'form': form, **self._context()},
        )


def index(request: WSGIRequest) -> HttpResponse:
    tags = Tag.objects.annotate(
        usages=Count('quotes'),
        row_number=Window(
            RowNumber(),
            order_by=(F('usages').desc(), F('name').asc()),
        ),
    ).filter(row_number__lte=10)

    context = {'tags': tags}

    query = Quote.objects

    if (tag_id := request.GET.get('tag')):
        context['current_tag'] = Tag.objects.filter(pk=tag_id).first()

        if context['current_tag']:
            query = query.filter(tags=tag_id)

    context['quotes'] = query.all()

    paginator = Paginator(range(len(context['quotes'])), size := 10)
    page = request.GET.get('page', 1)

    offset = size * (int(page) - 1)
    context['quotes'] = context['quotes'][offset:offset + size]

    try:
        page = paginator.page(page)
    except PageNotAnInteger:
        page = paginator.page(1)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    context['pager'] = {
        'Previous': page.previous_page_number if page.has_previous else '#',
        'Next': page.next_page_number if page.has_next else '#',
    }

    return render(request, 'fpq_core/index.html', context)

fpq/fpq_core/templates/fpq_core/form.html
{% extends 'fpq_core/index.html' %}

{% block title %}Form{% endblock %}

{% block content %}
  {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>
  {% endif %}

  <form method="post" class="needs-validation" novalidate>
    {% csrf_token %}

    {% block form %}{% endblock %}

    <button type="submit" class="btn btn-primary">
      {% block button %}Submit{% endblock %}
    </button>
  </form>
{% endblock %}

{% block footer %}
  <script>
    (() => {
      'use strict'

      const forms = document.querySelectorAll('.needs-validation')

      Array.from(forms).forEach(form => {
        form.addEventListener('submit', event => {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }

          form.classList.add('was-validated')
        }, false)
      })
    })()
  </script>
{% endblock %}

fpq/fpq_core/templates/fpq_core/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Quotes</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light{% if user.is_authenticated %} bg-dark" data-bs-theme="dark{% endif %}">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'fpq_core:index' %}">Quotes</a>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{% url 'fpq_core:index' %}"
              >
                Home
              </a>
            </li>

            {% if user.is_authenticated %}
              <li class="nav-item">
                <a
                  class="nav-link"
                  aria-current="page"
                  href="{% url 'fpq_author:create' %}"
                >
                  New author
                </a>
              </li>

              <li class="nav-item">
                <a
                  class="nav-link"
                  aria-current="page"
                  href="{% url 'fpq_quote:create' %}"
                >
                  New quote
                </a>
              </li>

              <li class="nav-item">
                <a
                  class="nav-link"
                  aria-current="page"
                  href="{% url 'fpq_scraper:scrape' %}"
                >
                  Scrape
                </a>
              </li>
            {% endif %}
          </ul>
          <span class="navbar-text">
            Hello,

            {% if user.is_anonymous %}
              guest
            {% else %}
              {{ user.username }}
            {% endif %}
          </span>
          <ul class="navbar-nav">
            {% if user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fpq_user:login' %}">
                  Sign in
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fpq_user:register' %}">
                  Sign up
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'fpq_user:logout' %}">
                  Logout
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
      <h1>
        {% block title %}
          Quotes
          {% if current_tag %}with tag <i>{{ current_tag }}</i>{% endif %}
        {% endblock %}
      </h1>

      {% for message in messages %}
        <div class="alert alert-danger" role="alert">{{ message }}</div>
      {% endfor %}

      <main class="row mt-5">
        <div class="col-9">
          {% block content %}
            {% if quotes %}
              {% load extract_tags %}

              {% for quote in quotes %}
                <div class="card mb-4">
                  <div class="card-body">
                    <blockquote class="blockquote mb-0">
                      <p>{{ quote.phrase }}</p>
                      <div class="row">
                        <div class="col">
                          {% for tag in quote.tags|tags %}
                            <a
                              href="{% url 'fpq_core:index' %}?tag={{ tag.id }}"
                              class="
                                badge
                                {% if current_tag == tag %}
                                  text-bg-success
                                {% else %}
                                  text-bg-secondary
                                {% endif %}
                                link-underline
                                link-underline-opacity-0
                              "
                            >
                              {{ tag }}
                            </a>
                          {% endfor %}
                        </div>
                        <div class="col">
                          <footer class="blockquote-footer text-end mt-0 mb-0">
                            <a
                              href="{% url 'fpq_author:detail' quote.author.id %}"
                              class="link-secondary link-underline-light link-offset-2"
                            >
                              {{ quote.author }}
                            </a>
                          </footer>
                        </div>
                      </div>
                    </blockquote>
                  </div>
                </div>
              {% endfor %}

              <nav aria-label="Other quotes">
                <ul class="pagination justify-content-center">
                  {% for label, page in pager.items %}
                    <li class="page-item{% if not page != '#' %} disabled{% endif %}">
                      {% if page != '#' %}
                        <a
                          href="{% url 'fpq_core:index' %}?{% if current_tag %}tag={{ current_tag.id }}&{% endif %}page={{ page }}"
                          class="page-link"
                        >
                          {{ label }}
                        </a>
                      {% else %}
                        <span class="page-link">{{ label }}</span>
                      {% endif %}
                    </li>
                  {% endfor %}
                </ul>
              </nav>
            {% else %}
              <p>Welcome to the website!</p>
            {% endif %}
          {% endblock %}
        </div>
        <div class="col">
          {% if tags %}
            <div class="card">
              <div class="card-header text-center">Top Ten tags</div>
              <div class="list-group list-group-flush">
                {% for tag in tags %}
                  <a
                    href="{% url 'fpq_core:index' %}?tag={{ tag.id }}"
                    class="
                      list-group-item
                      list-group-item-action
                      {% if current_tag == tag %}active{% endif %}
                      d-flex
                      justify-content-between
                      align-items-center
                    "
                  >
                    {{ tag.name }}
                    <span class="badge text-bg-secondary rounded-pill">
                      {{ tag.usages }}
                    </span>
                  </a>
                {% endfor %}
              </div>
            </div>
          {% endif %}
        </div>
      </main>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    {% block footer %}{% endblock %}
  </body>
</html>