fpq/fpq/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('fpq_core.urls')),
    *[
        path(f'{name}/', include(f'fpq_{name}.urls'))
        for name in ('user', 'author', 'quote')
    ],
    path('scrape/', include('fpq_scraper.urls')),
    path('admin/', admin.site.urls),
]

fpq/fpq_core/urls.py
from django.urls import path

from .views import index

app_name = 'fpq_core'

urlpatterns = [
    path('', index, name='index'),
]

fpq/fpq_user/urls.py
from django.contrib.auth.views import LoginView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordResetDoneView
from django.urls import path

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView, signout

app_name = 'fpq_user'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(
            template_name='fpq_user/login.html',
            form_class=LoginForm,
            redirect_authenticated_user=True,
        ),
        name='login',
    ),
    path('logout/', signout, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path(
        'reset-password/',
        ResetPasswordView.as_view(),
        name='password_reset',
    ),
    path(
        'reset-password/done/',
        PasswordResetDoneView.as_view(
            template_name='fpq_user/password_reset_done.html',
        ),
        name='password_reset_done',
    ),
    path(
        'reset-password/confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='fpq_user/password_reset_confirm.html',
            success_url='/user/reset-password/complete/',
        ),
        name='password_reset_confirm',
    ),
    path(
        'reset-password/complete/',
        PasswordResetCompleteView.as_view(
            template_name='fpq_user/password_reset_complete.html',
        ),
        name='password_reset_complete',
    ),
]

fpq/fpq_user/models.py
from django.db import models

# Create your models here.

fpq/fpq_user/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField, EmailField, EmailInput, PasswordInput, \
    TextInput

from fpq_core.forms import FormHelper


USERNAME = {'min_length': 3, 'max_length': 16, 'required': True}


class LoginForm(AuthenticationForm):
    username = CharField(
        widget=TextInput(FormHelper.attributes('username')),
        **USERNAME,
    )

    password = CharField(
        required=True,
        widget=PasswordInput(FormHelper.attributes('password')),
    )

    def __init__(self, *args: tuple, **kwargs: dict) -> None:
        super().__init__(*args, **kwargs)

        FormHelper.validate(self)

    class Meta:
        model = User
        fields = ('username', 'password')


class RegisterForm(UserCreationForm):
    username = CharField(
        widget=TextInput(FormHelper.attributes('username')),
        **USERNAME,
    )

    email = EmailField(
        min_length=7,
        max_length=40,
        required=True,
        widget=EmailInput(FormHelper.attributes('email')),
    )

    password1 = CharField(
        required=True,
        widget=PasswordInput(FormHelper.attributes('password')),
    )

    password2 = CharField(
        required=True,
        widget=PasswordInput(FormHelper.attributes('confirm-password')),
    )

    def __init__(self, *args: tuple, **kwargs: dict) -> None:
        super().__init__(*args, **kwargs)

        FormHelper.validate(self)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

fpq/fpq_user/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy

from fpq_core.views import FormView
from .forms import RegisterForm


class RegisterView(FormView):
    template_name = 'fpq_user/register.html'
    form_class = RegisterForm

    def _guest(self) -> bool:
        return False


class ResetPasswordView(PasswordResetView, SuccessMessageMixin):
    template_name = 'fpq_user/password_reset.html'
    email_template_name = 'fpq_user/password_reset_email.html'
    html_email_template_name = 'fpq_user/password_reset_email.html'
    success_url = reverse_lazy('fpq_user:password_reset_done')
    success_message = ('An email with instructions to reset your password has '
                       'been sent to %(email)s.')
    subject_template_name = 'fpq_user/password_reset_subject.txt'


@login_required
def signout(request: WSGIRequest) -> HttpResponsePermanentRedirect:
    logout(request)

    return redirect('fpq_core:index')

fpq/fpq_user/templates/fpq_user/login.html
{% extends 'fpq_core/form.html' %}

{% block title %}Sign in{% endblock %}

{% block form %}
  <div class="row mb-3">
    <label for="username" class="col-sm-2 col-form-label">Username</label>
    <div class="col-sm-10">
      {{ form.username }}

      {% if form.errors.username %}
        <div id="username-error" class="invalid-feedback">
          {{ form.errors.username }}
        </div>
      {% endif %}
    </div>
  </div>

  {% block fields %}
    <div class="row mb-3">
      <label for="password" class="col-sm-2 col-form-label">Password</label>
      <div class="col-sm-10">
        {{ form.password }}

        {% if form.errors.password %}
          <div id="password-error" class="invalid-feedback">
            {{ form.errors.password }}
          </div>
        {% endif %}
      </div>
    </div>
  {% endblock %}

  <input type="hidden" name="next" value="{% url 'fpq_core:index' %}">

  <div class="row mb-3">
    <a href="{% url 'fpq_user:password_reset' %}">Forgot Password?</a>
  </div>
{% endblock %}

fpq/fpq_user/templates/fpq_user/password_reset.html
{% extends 'fpq_core/form.html' %}

{% block title %}Password reset{% endblock %}

{% block form %}<div class="row mb-3">{{ form.as_p }}</div>{% endblock %}

{% block button %}Request password reset{% endblock %}

fpq/fpq_user/templates/fpq_user/password_reset_complete.html
{% extends 'fpq_core/index.html' %}

{% block title %}Password reset complete!{% endblock %}

fpq/fpq_user/templates/fpq_user/password_reset_confirm.html
{% extends 'fpq_user/password_reset.html' %}

{% block title %}Enter new password{% endblock %}

{% block button %}Save new password{% endblock %}

fpq/fpq_user/templates/fpq_user/password_reset_done.html
{% extends 'fpq_core/index.html' %}

{% block title %}Password reset request sent{% endblock %}

{% block content %}
    <p>We've emailed you with instructions on how to reset your password.</p>
{% endblock %}

fpq/fpq_user/templates/fpq_user/password_reset_email.html
{% autoescape off %}
<body>
  <p>Hi {{ user.username }},</p>
  <p>You requested a password reset for your account. Please follow this link to set a new password:</p>
  <p>
    <a href="{{ protocol }}://{{ domain }}{% url 'fpq_user:password_reset_confirm' uidb64=uid token=token %}">
      Set new password
    </a>
  </p>
  <p>If you didn't request a password reset, please ignore this email.</p>
  <p>Thanks,</p>
  <p>The Our Team</p>
</body>
{% endautoescape %}

fpq/fpq_user/templates/fpq_user/register.html
{% extends 'fpq_user/login.html' %}

{% block title %}Create a new user{% endblock %}

{% block fields %}
  <div class="row mb-3">
    <label for="email" class="col-sm-2 col-form-label">E-mail</label>
    <div class="col-sm-10">
      {{ form.email }}

      {% if form.errors.email %}
        <div id="email-error" class="invalid-feedback">
          {{ form.errors.email }}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="row mb-3">
    <label for="password" class="col-sm-2 col-form-label">Password</label>
    <div class="col-sm-10">
      {{ form.password1 }}

      {% if form.errors.password1 %}
        <div id="password-error" class="invalid-feedback">
          {{ form.errors.password1 }}
        </div>
      {% endif %}
    </div>
  </div>

  <div class="row mb-3">
    <label for="confirm-password" class="col-sm-2 col-form-label">
      Confirm password
    </label>
    <div class="col-sm-10">
      {{ form.password2 }}

      {% if form.errors.password2 %}
        <div id="confirm-password-error" class="invalid-feedback">
          {{ form.errors.password2 }}
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}